name: digitalocean_deploy

on:
  push:
    branches: [ main ]
jobs:
  Build:
    runs-on: self-hosted
  
  steps:
    - uses: actions/checkout@main
    - name: Create .env 
      run: echo 'WP_PORT=${{ secrets.WP_PORT }}' > .env
    #Reboot.
    - name: Down container
      run: docker-compose down --volumes
    - name: Run build
      run: docker-compose up -d 
      
