name: digitalocean_deploy

on:
  push:
    branches: [ main ]
jobs:
  Build:
    runs-on: self-hosted
  
    steps:
      - uses: actions/checkout@main
      - name: "Create .env"
        run: echo 'WP_PORT=${{ secrets.WP_PORT }}' > .env
             echo 'PHP_ADMIN_PW=${{ secrets.PHP_ADMIN_PW }}' > .env


    #Reboot.
      - name: Run build
        run: docker-compose up -d
      
